{
 "title": "Home Lab Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "name",
    "label": "Host:",
    "query": "label_values(node_uname_info{job=~\"$job\"}, nodename)"
   },
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(node_uname_info{nodename=\"$name\"}, instance)"
   },
   {
    "name": "port",
    "label": "Port",
    "query": "label_values(node_uname_info{instance=~\"$node:(.*)\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Busy",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$node:$port\",job=~\"$job\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Sys Load (5m avg)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "avg(node_load5{instance=~\"$node:$port\",job=~\"$job\"}) /  count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Sys Load (15m avg)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "avg(node_load15{instance=~\"$node:$port\",job=~\"$job\"}) /  count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\"$node:$port\",job=~\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_SwapFree_bytes{instance=~\"$node:$port\",job=~\"$job\"}) / (node_memory_SwapTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"} )) * 100"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$node:$port\",job=~\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\"$node:$port\",job=~\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$node:$port\",job=~\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$node:$port\",job=~\"$job\"} - node_boot_time_seconds{instance=~\"$node:$port\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$node:$port\",job=~\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"}"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=\"system\",instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='user',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode='iowait',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(irate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (irate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$node:$port\",job=~\"$job\"}[5m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_MemFree_bytes{instance=~\"$node:$port\",job=~\"$job\"} - (node_memory_Cached_bytes{instance=~\"$node:$port\",job=~\"$job\"} + node_memory_Buffers_bytes{instance=~\"$node:$port\",job=~\"$job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$node:$port\",job=~\"$job\"} + node_memory_Buffers_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_SwapFree_bytes{instance=~\"$node:$port\",job=~\"$job\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"$node:$port\",job=~\"$job\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{instance=~\"$node:$port\",job=~\"$job\",device!~'rootfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Memory Stack",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 15 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_MemFree_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_Buffers_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_Cached_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_Slab_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_PageTables_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_SwapCached_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "Apps"
    },
    {
     "expr": "node_memory_PageTables_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "PageTables"
    },
    {
     "expr": "node_memory_SwapCached_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "SwapCache"
    },
    {
     "expr": "node_memory_Slab_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "Slab"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "Cache"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "Unused"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~\"$node:$port\",job=~\"$job\"} - node_memory_SwapFree_bytes{instance=~\"$node:$port\",job=~\"$job\"})",
     "legendFormat": "Swap"
    },
    {
     "expr": "node_memory_HardwareCorrupted_bytes{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "Hardware Corrupted"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bps", "label": "bits out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])*8",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"$node:$port\",job=~\"$job\"}[5m])*8",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "counter" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{instance=~\"$node:$port\",job=~\"$job\"}",
     "legendFormat": "Load 15m"
    }
   ]
  }
 ]
}